apiVersion: v1
kind: Service
metadata:
  name: weather-pred-ml-service
spec:
  selector:
    app: weather-pred-ml
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-pred-ml
spec:
  selector:
    matchLabels:
      app: weather_pred_ml
  replicas: 4
  template:
    metadata:
      labels:
        app: weather_pred_ml
    spec:
      containers:
      - name: weather-pred-ml
        image: weather-pred-ml:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
